### ISSUE TITLE
last contact

### ISSUE THREAD

**Issue by ruphy** [rspurgeon/dots#2]
Hey Rick,

Thank you for writing back, I'm sorry you deleted the issue. This will be my last message to you.

I know rick@hey.com is not your email, that is *my* email.

The many emails I have received are for a certain Rick Spurgeon living in the Chicago Area. I have received emails for preschooling and job fairs, among other things. LinkedIn took me to you. The last one comes from: Huntley Health & Fitness Center. I have also received a lot of other email that assumed I live in Chicago (halfway around the globe from where I am).

here's a snapshot of what I have:

<img width="613" alt="image" src="https://github.com/rspurgeon/dots/assets/2030/b3497b4a-6364-42fb-bfbd-91e45b88ab66">

As it's the first email with a last name, I found you. If that's not you, I'll delete all emails and apologies for the time taken. Let me know.

Riccardo

**Comment by ruphy** [comment]
I also don't mean to bother you. I am a fellow technologist and I am just trying to do the right thing here. If that's not you, I'll be out of your inbox in a second.

**Comment by rspurgeon** [comment]
@ruphy Sorry for the (my) confusion. I will email you.
